server:
  port: 10042
eureka:
  instance:
    appname: 用户中心
spring:
  application:
    name: busi
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:10032/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:10032/oauth/token
      grant-type: client_credentials,password
      scope: server
