server:
  port: 10042
eureka:
  instance:
    appname: 业务中心
spring:
  application:
    name: user
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:10033/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:10033/oauth/token
      grant-type: client_credentials,password
      scope: server
